USE DATABASE {{ DATABASE }};

-- The owner-rights procedure needs direct table privileges; the Streamlit app
-- itself still reads only governed views and writes only through this procedure.
GRANT SELECT ON TABLE GOVERNANCE.APPROVAL_STEWARDS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.CATALOG_RESOURCES TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.SOURCE_DOCUMENT_SNAPSHOTS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.SCHEMA_SNAPSHOTS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.DATASET_QUALITY_ASSESSMENTS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.SOURCE_ACCESS_PROFILES TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.SCHEMA_CHANGE_EVENTS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.MANUAL_REVIEW_DECISIONS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT INSERT ON TABLE GOVERNANCE.MANUAL_REVIEW_DECISIONS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT INSERT ON TABLE GOVERNANCE.DATA_SOURCE_VERSIONS TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
