USE DATABASE {{ DATABASE }};

-- The worker may load only the CDC RAW target and transient stage. It cannot
-- approve a source, modify the approval app, or access the Alpha POC database.
GRANT USAGE ON SCHEMA RAW TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON SCHEMA GOVERNANCE TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON TABLE GOVERNANCE.DATA_SOURCE_VERSIONS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE GOVERNANCE.INGESTION_RUNS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.INGESTION_REQUESTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.RAW_ARTIFACTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.DATA_QUALITY_RESULTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE RAW.CDC_LYME_X5J9_WYBP TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT READ, WRITE ON STAGE RAW.INGESTION_TRANSIENT_STAGE TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
