USE DATABASE {{ DATABASE }};

-- dbt builds only the governed CDC relations. It may read approved RAW
-- records but retains no ability to review candidates or alter governance.
GRANT SELECT ON TABLE RAW.CDC_LYME_X5J9_WYBP TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
