USE DATABASE {{ DATABASE }};

-- Reassert V019's scoped grants after a manually recorded deployment did not
-- complete all grant statements. Preserve the append-only migration ledger;
-- do not delete or rewrite either V019 record.
GRANT SELECT ON TABLE RAW.CDC_LYME_X5J9_WYBP TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STAGING TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CONFORMED TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
