USE DATABASE {{ DATABASE }};

-- Knowledge-graph v1 is additive and does not alter the Alpha LANDING or
-- PRESENTATION objects. All mutable application actions use owner-rights
-- procedures; runtime roles receive no direct table-write grants.
CREATE SCHEMA IF NOT EXISTS KNOWLEDGE_GRAPH;

CREATE TABLE IF NOT EXISTS GOVERNANCE.KG_CONFIGURATION_VERSIONS (
  configuration_version VARCHAR PRIMARY KEY,
  contract_sha256 VARCHAR NOT NULL,
  configuration VARIANT NOT NULL,
  activated_at TIMESTAMP_LTZ,
  recorded_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  recorded_by VARCHAR NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PAPERS (
  pmid VARCHAR PRIMARY KEY,
  pmcid VARCHAR,
  title VARCHAR NOT NULL,
  journal VARCHAR,
  publication_date DATE,
  publication_types ARRAY NOT NULL,
  language VARCHAR NOT NULL,
  abstract VARCHAR,
  access_status VARCHAR NOT NULL DEFAULT 'unknown',
  state VARCHAR NOT NULL DEFAULT 'discovered',
  final_review_decision_id VARCHAR,
  full_text_object_key VARCHAR,
  content_sha256 VARCHAR,
  configuration_version VARCHAR NOT NULL,
  discovered_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT ck_kg_paper_state CHECK (state IN (
    'discovered','awaiting_review','approved','rejected','deferred','access_rejected',
    'ready_for_extraction','extracting','retry_pending','retry_exhausted','processed'))
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PAPER_QUERY_MATCHES (
  query_match_id VARCHAR PRIMARY KEY,
  pmid VARCHAR NOT NULL,
  family VARCHAR NOT NULL,
  query_sha256 VARCHAR NOT NULL,
  discovery_run_id VARCHAR NOT NULL,
  matched_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UNIQUE (pmid, family, query_sha256)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PUBMED_DISCOVERY_RUNS (
  discovery_run_id VARCHAR PRIMARY KEY,
  family VARCHAR NOT NULL,
  query_text VARCHAR NOT NULL,
  query_sha256 VARCHAR NOT NULL,
  webenv VARCHAR,
  query_key VARCHAR,
  result_count NUMBER,
  next_retstart NUMBER NOT NULL DEFAULT 0,
  batch_size NUMBER NOT NULL DEFAULT 200,
  status VARCHAR NOT NULL,
  raw_artifact_id VARCHAR,
  request_evidence VARIANT NOT NULL,
  started_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  finished_at TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PAPER_STATE_EVENTS (
  paper_state_event_id VARCHAR PRIMARY KEY,
  pmid VARCHAR NOT NULL,
  from_state VARCHAR,
  to_state VARCHAR NOT NULL,
  reason VARCHAR NOT NULL,
  correlation_id VARCHAR NOT NULL,
  actor VARCHAR NOT NULL,
  occurred_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PAPER_REVIEW_DECISIONS (
  paper_review_decision_id VARCHAR PRIMARY KEY,
  batch_id VARCHAR NOT NULL,
  pmid VARCHAR NOT NULL,
  decision VARCHAR NOT NULL,
  rationale VARCHAR NOT NULL,
  reviewer_username VARCHAR NOT NULL,
  app_version VARCHAR NOT NULL,
  correlation_id VARCHAR NOT NULL,
  decided_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT ck_kg_review_decision CHECK (decision IN ('approved','rejected','deferred'))
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.EXTRACTION_ATTEMPTS (
  extraction_attempt_id VARCHAR PRIMARY KEY,
  pmid VARCHAR NOT NULL,
  attempt_number NUMBER NOT NULL,
  provider_route VARCHAR NOT NULL,
  model_identifier VARCHAR NOT NULL,
  estimated_input_tokens NUMBER NOT NULL,
  request_sha256 VARCHAR NOT NULL,
  status VARCHAR NOT NULL,
  error_class VARCHAR,
  started_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  finished_at TIMESTAMP_LTZ,
  UNIQUE (pmid, attempt_number)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.GRAPH_PUBLICATION_RECEIPTS (
  graph_receipt_id VARCHAR PRIMARY KEY,
  pmid VARCHAR NOT NULL,
  contribution_sha256 VARCHAR NOT NULL,
  neo4j_transaction_id VARCHAR NOT NULL,
  node_count NUMBER NOT NULL,
  passage_count NUMBER NOT NULL,
  edge_count NUMBER NOT NULL,
  published_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UNIQUE (pmid, contribution_sha256)
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.LLM_BUDGET_USAGE (
  budget_usage_id VARCHAR PRIMARY KEY,
  workload VARCHAR NOT NULL,
  request_id VARCHAR NOT NULL,
  provider VARCHAR NOT NULL,
  model_identifier VARCHAR NOT NULL,
  estimated_cost_usd NUMBER(12,6) NOT NULL,
  actual_cost_usd NUMBER(12,6),
  status VARCHAR NOT NULL,
  recorded_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UNIQUE (workload, request_id)
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.KG_CONVERSATIONS (
  conversation_id VARCHAR PRIMARY KEY,
  token_hash VARCHAR NOT NULL UNIQUE,
  network_hash VARCHAR NOT NULL,
  created_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  expires_at TIMESTAMP_LTZ NOT NULL,
  last_turn_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.KG_CONVERSATION_TURNS (
  turn_id VARCHAR PRIMARY KEY,
  conversation_id VARCHAR NOT NULL,
  request_id VARCHAR NOT NULL UNIQUE,
  role VARCHAR NOT NULL,
  body VARCHAR NOT NULL,
  status VARCHAR NOT NULL,
  created_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.KG_TURN_CITATIONS (
  turn_id VARCHAR NOT NULL,
  citation_id VARCHAR NOT NULL,
  pmid VARCHAR NOT NULL,
  passage_id VARCHAR NOT NULL,
  claim_ids ARRAY NOT NULL,
  PRIMARY KEY (turn_id, citation_id)
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.KG_OPERATIONAL_AUDIT_EVENTS (
  audit_event_id VARCHAR PRIMARY KEY,
  event_type VARCHAR NOT NULL,
  severity VARCHAR NOT NULL,
  correlation_id VARCHAR NOT NULL,
  details VARIANT NOT NULL,
  occurred_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW GOVERNANCE.V_KG_PAPER_REVIEW_QUEUE AS
SELECT p.pmid, p.pmcid, p.title, p.journal, p.publication_date,
       p.publication_types, p.language, p.abstract, p.access_status, p.state,
       p.discovered_at, p.configuration_version,
       'https://pubmed.ncbi.nlm.nih.gov/' || p.pmid || '/' AS pubmed_url,
       ARRAY_AGG(DISTINCT m.family) WITHIN GROUP (ORDER BY m.family) AS query_families
FROM KNOWLEDGE_GRAPH.PAPERS p
JOIN KNOWLEDGE_GRAPH.PAPER_QUERY_MATCHES m ON m.pmid = p.pmid
WHERE p.state IN ('awaiting_review', 'deferred')
GROUP BY ALL;

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_RECORD_PAPER_REVIEW_BATCH(
  PMIDS ARRAY, DECISION VARCHAR, RATIONALE VARCHAR, REVIEWER_USERNAME VARCHAR,
  APP_VERSION VARCHAR, CORRELATION_ID VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  unauthorized EXCEPTION (-20101, 'Reviewer is not an active data steward');
  invalid_decision EXCEPTION (-20102, 'Unsupported paper review decision');
  invalid_rationale EXCEPTION (-20103, 'A 10-10000 character rationale is required');
  invalid_selection EXCEPTION (-20104, 'Selection contains an ineligible paper');
  steward_count NUMBER;
  eligible_count NUMBER;
  batch_id VARCHAR DEFAULT UUID_STRING();
BEGIN
  IF (DECISION NOT IN ('approved','rejected','deferred')) THEN RAISE invalid_decision; END IF;
  IF (RATIONALE IS NULL OR LENGTH(TRIM(RATIONALE)) < 10 OR LENGTH(RATIONALE) > 10000)
    THEN RAISE invalid_rationale; END IF;
  SELECT COUNT(*) INTO :steward_count FROM GOVERNANCE.APPROVAL_STEWARDS
    WHERE username = :REVIEWER_USERNAME AND is_active = TRUE;
  IF (steward_count <> 1) THEN RAISE unauthorized; END IF;
  SELECT COUNT(*) INTO :eligible_count FROM KNOWLEDGE_GRAPH.PAPERS p,
    LATERAL FLATTEN(INPUT => :PMIDS) selected
    WHERE p.pmid = selected.value::VARCHAR AND p.state IN ('awaiting_review','deferred');
  IF (eligible_count <> ARRAY_SIZE(PMIDS) OR eligible_count = 0) THEN RAISE invalid_selection; END IF;

  INSERT INTO KNOWLEDGE_GRAPH.PAPER_REVIEW_DECISIONS
    SELECT UUID_STRING(), :batch_id, selected.value::VARCHAR, :DECISION, :RATIONALE,
           :REVIEWER_USERNAME, :APP_VERSION, :CORRELATION_ID, CURRENT_TIMESTAMP()
    FROM TABLE(FLATTEN(INPUT => :PMIDS)) selected;
  INSERT INTO KNOWLEDGE_GRAPH.PAPER_STATE_EVENTS
    SELECT UUID_STRING(), p.pmid, p.state, :DECISION, 'paper_review', :CORRELATION_ID,
           :REVIEWER_USERNAME, CURRENT_TIMESTAMP()
    FROM KNOWLEDGE_GRAPH.PAPERS p, TABLE(FLATTEN(INPUT => :PMIDS)) selected
    WHERE p.pmid = selected.value::VARCHAR;
  UPDATE KNOWLEDGE_GRAPH.PAPERS p SET state = :DECISION,
      final_review_decision_id = d.paper_review_decision_id, updated_at = CURRENT_TIMESTAMP()
    FROM KNOWLEDGE_GRAPH.PAPER_REVIEW_DECISIONS d
    WHERE d.batch_id = :batch_id AND d.pmid = p.pmid;
  RETURN OBJECT_CONSTRUCT('batch_id', :batch_id, 'paper_count', :eligible_count);
END;
$$;

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  WORKLOAD VARCHAR, REQUEST_ID VARCHAR, PROVIDER VARCHAR, MODEL_IDENTIFIER VARCHAR,
  ESTIMATED_COST_USD NUMBER, DAILY_LIMIT_USD NUMBER, MONTHLY_LIMIT_USD NUMBER
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  daily_used NUMBER;
  monthly_used NUMBER;
  allowed BOOLEAN;
BEGIN
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :daily_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('day', CURRENT_TIMESTAMP());
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :monthly_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('month', CURRENT_TIMESTAMP());
  allowed := daily_used + ESTIMATED_COST_USD <= DAILY_LIMIT_USD
             AND monthly_used + ESTIMATED_COST_USD <= MONTHLY_LIMIT_USD;
  IF (allowed) THEN
    INSERT INTO GOVERNANCE.LLM_BUDGET_USAGE VALUES
      (UUID_STRING(), :WORKLOAD, :REQUEST_ID, :PROVIDER, :MODEL_IDENTIFIER,
       :ESTIMATED_COST_USD, NULL, 'reserved', CURRENT_TIMESTAMP());
  END IF;
  RETURN OBJECT_CONSTRUCT('allowed', :allowed, 'daily_used_usd', :daily_used,
                          'monthly_used_usd', :monthly_used);
END;
$$;

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(
  CONVERSATION_ID VARCHAR, TOKEN_HASH VARCHAR, NETWORK_HASH VARCHAR, TURN_ID VARCHAR,
  REQUEST_ID VARCHAR, ROLE VARCHAR, BODY VARCHAR, STATUS VARCHAR, CITATIONS VARIANT
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  token_mismatch EXCEPTION (-20110, 'Conversation capability is invalid');
  existing_count NUMBER;
  matching_count NUMBER;
BEGIN
  SELECT COUNT(*), COUNT_IF(token_hash = :TOKEN_HASH)
    INTO :existing_count, :matching_count
    FROM GOVERNANCE.KG_CONVERSATIONS WHERE conversation_id = :CONVERSATION_ID;
  IF (existing_count = 1 AND matching_count <> 1) THEN RAISE token_mismatch; END IF;
  MERGE INTO GOVERNANCE.KG_CONVERSATIONS target
  USING (SELECT :CONVERSATION_ID id) source ON target.conversation_id = source.id
  WHEN NOT MATCHED THEN INSERT
    (conversation_id, token_hash, network_hash, expires_at)
    VALUES (:CONVERSATION_ID, :TOKEN_HASH, :NETWORK_HASH, DATEADD(day, 30, CURRENT_TIMESTAMP()))
  WHEN MATCHED AND target.token_hash = :TOKEN_HASH THEN UPDATE SET
    last_turn_at = CURRENT_TIMESTAMP(), expires_at = DATEADD(day, 30, CURRENT_TIMESTAMP());
  INSERT INTO GOVERNANCE.KG_CONVERSATION_TURNS
    (turn_id, conversation_id, request_id, role, body, status)
    VALUES (:TURN_ID, :CONVERSATION_ID, :REQUEST_ID, :ROLE, :BODY, :STATUS);
  INSERT INTO GOVERNANCE.KG_TURN_CITATIONS
    SELECT :TURN_ID, value:citation_id::VARCHAR, value:pmid::VARCHAR,
           value:passage_id::VARCHAR, value:claim_ids::ARRAY
    FROM TABLE(FLATTEN(INPUT => :CITATIONS));
  RETURN OBJECT_CONSTRUCT('persisted', TRUE, 'expires_in_days', 30);
END;
$$;

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_VERIFY_KG_CONVERSATION_TOKEN(
  CONVERSATION_ID VARCHAR, TOKEN_HASH VARCHAR
)
RETURNS BOOLEAN
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE match_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO :match_count FROM GOVERNANCE.KG_CONVERSATIONS
    WHERE conversation_id = :CONVERSATION_ID AND token_hash = :TOKEN_HASH
      AND expires_at > CURRENT_TIMESTAMP();
  RETURN match_count = 1;
END;
$$;

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_PURGE_EXPIRED_KG_CONVERSATIONS()
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS
$$
DECLARE deleted_count NUMBER;
BEGIN
  DELETE FROM GOVERNANCE.KG_TURN_CITATIONS WHERE turn_id IN (
    SELECT t.turn_id FROM GOVERNANCE.KG_CONVERSATION_TURNS t
    JOIN GOVERNANCE.KG_CONVERSATIONS c USING (conversation_id)
    WHERE c.expires_at <= CURRENT_TIMESTAMP());
  DELETE FROM GOVERNANCE.KG_CONVERSATION_TURNS WHERE conversation_id IN (
    SELECT conversation_id FROM GOVERNANCE.KG_CONVERSATIONS
    WHERE expires_at <= CURRENT_TIMESTAMP());
  DELETE FROM GOVERNANCE.KG_CONVERSATIONS WHERE expires_at <= CURRENT_TIMESTAMP();
  deleted_count := SQLROWCOUNT;
  RETURN OBJECT_CONSTRUCT('deleted_conversations', :deleted_count);
END;
$$;

CREATE TASK IF NOT EXISTS GOVERNANCE.PURGE_EXPIRED_KG_CONVERSATIONS_TASK
  WAREHOUSE = OH_LYME_{{ ENV }}_INGEST_XS_WH
  SCHEDULE = 'USING CRON 30 4 * * * America/Denver'
AS CALL GOVERNANCE.SP_PURGE_EXPIRED_KG_CONVERSATIONS();
ALTER TASK GOVERNANCE.PURGE_EXPIRED_KG_CONVERSATIONS_TASK RESUME;

GRANT USAGE ON SCHEMA KNOWLEDGE_GRAPH TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA KNOWLEDGE_GRAPH
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON VIEW GOVERNANCE.V_KG_PAPER_REVIEW_QUEUE
  TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RECORD_PAPER_REVIEW_BATCH(ARRAY, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR)
  TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;

-- The API runtime's only writes are mediated by these procedures.
CREATE ROLE IF NOT EXISTS OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON DATABASE {{ DATABASE }} TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON SCHEMA PRESENTATION TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT SELECT ON ALL VIEWS IN SCHEMA PRESENTATION TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON SCHEMA GOVERNANCE TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_VERIFY_KG_CONVERSATION_TOKEN(VARCHAR, VARCHAR)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
