USE DATABASE {{ DATABASE }};

-- V025 deliberately introduced the literature namespace. Its schema-wide
-- INSERT/UPDATE grant was broader than the worker's defined ledger contract.
-- Keep the human-review procedure owner-only and limit the worker to the
-- exact tables it must mutate while retaining the API procedure-only writes.
REVOKE INSERT, UPDATE ON ALL TABLES IN SCHEMA KNOWLEDGE_GRAPH
  FROM ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;

GRANT SELECT, INSERT, UPDATE ON TABLE KNOWLEDGE_GRAPH.PAPERS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE KNOWLEDGE_GRAPH.PAPER_QUERY_MATCHES
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE KNOWLEDGE_GRAPH.PUBMED_DISCOVERY_RUNS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE KNOWLEDGE_GRAPH.PAPER_STATE_EVENTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE KNOWLEDGE_GRAPH.EXTRACTION_ATTEMPTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE KNOWLEDGE_GRAPH.GRAPH_PUBLICATION_RECEIPTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;

-- PubMed responses are immutable source artifacts, so the worker also needs
-- the same narrow artifact insertion permission granted to the CDC connector.
GRANT INSERT ON TABLE GOVERNANCE.RAW_ARTIFACTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
