USE DATABASE {{ DATABASE }};

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH.PMC_FULL_TEXT_ARTIFACTS (
  pmid VARCHAR PRIMARY KEY,
  pmcid VARCHAR NOT NULL,
  artifact_id VARCHAR NOT NULL,
  object_key VARCHAR NOT NULL,
  license_url VARCHAR NOT NULL,
  jats_sha256 VARCHAR NOT NULL,
  text_sha256 VARCHAR NOT NULL,
  admitted_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
GRANT SELECT, INSERT ON TABLE KNOWLEDGE_GRAPH.PMC_FULL_TEXT_ARTIFACTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
