USE DATABASE {{ DATABASE }};

-- One claimed paper is the bounded unit of extraction. These additive columns
-- bind an immutable PMC artifact, cost/model attempt, and graph receipt without
-- changing the Alpha POC or granting the runtime approval authority.
ALTER TABLE KNOWLEDGE_GRAPH.EXTRACTION_ATTEMPTS
  ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMP_LTZ;
ALTER TABLE KNOWLEDGE_GRAPH.EXTRACTION_ATTEMPTS
  ADD COLUMN IF NOT EXISTS method_version VARCHAR NOT NULL DEFAULT 'kg-v1.0.0';

ALTER TABLE KNOWLEDGE_GRAPH.GRAPH_PUBLICATION_RECEIPTS
  ADD COLUMN IF NOT EXISTS extraction_attempt_id VARCHAR;
ALTER TABLE KNOWLEDGE_GRAPH.GRAPH_PUBLICATION_RECEIPTS
  ADD COLUMN IF NOT EXISTS artifact_id VARCHAR;

GRANT SELECT, INSERT, UPDATE ON TABLE KNOWLEDGE_GRAPH.EXTRACTION_ATTEMPTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE KNOWLEDGE_GRAPH.GRAPH_PUBLICATION_RECEIPTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
