USE DATABASE {{ DATABASE }};

-- Keep the paper-review procedure owner-rights boundary separate from the
-- Streamlit caller role.  The caller can invoke the procedure, but cannot
-- directly read or modify the underlying knowledge-graph tables.
CREATE ROLE IF NOT EXISTS OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;

GRANT USAGE ON DATABASE {{ DATABASE }}
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;
GRANT USAGE ON SCHEMA GOVERNANCE
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;
GRANT USAGE ON SCHEMA KNOWLEDGE_GRAPH
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;

GRANT SELECT ON TABLE GOVERNANCE.APPROVAL_STEWARDS
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;
GRANT SELECT, UPDATE ON TABLE KNOWLEDGE_GRAPH.PAPERS
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;
GRANT SELECT, INSERT ON TABLE KNOWLEDGE_GRAPH.PAPER_REVIEW_DECISIONS
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;
GRANT INSERT ON TABLE KNOWLEDGE_GRAPH.PAPER_STATE_EVENTS
  TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER;

GRANT OWNERSHIP ON PROCEDURE GOVERNANCE.SP_RECORD_PAPER_REVIEW_BATCH(
  ARRAY, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR
) TO ROLE OH_LYME_{{ ENV }}_KG_PAPER_REVIEW_OWNER COPY CURRENT GRANTS;

-- The review-console role retains only invoke access.  Do not grant the owner
-- role to users, Streamlit, or the pipeline runtime.
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RECORD_PAPER_REVIEW_BATCH(
  ARRAY, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR
) TO ROLE OH_LYME_{{ ENV }}_STREAMLIT_OWNER;
