USE DATABASE {{ DATABASE }};

-- The evidence-only CDC onboarding command records its own immutable catalog,
-- request, artifact, schema, and assessment evidence. These narrow writes are
-- distinct from source approval and full-ingestion privileges.
GRANT INSERT ON TABLE GOVERNANCE.CATALOG_DATASETS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.CATALOG_RESOURCES TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE GOVERNANCE.SOURCE_ACCESS_PROFILES
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.SOURCE_DOCUMENT_SNAPSHOTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.SCHEMA_SNAPSHOTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT INSERT ON TABLE GOVERNANCE.DATASET_QUALITY_ASSESSMENTS
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
