USE DATABASE {{ DATABASE }};

CREATE TABLE IF NOT EXISTS CONFORMED.CDC_VALIDATED_SNAPSHOTS (
  source_record_id VARCHAR, payload VARIANT, data_source_version_id VARCHAR,
  ingestion_run_id VARCHAR, artifact_id VARCHAR, county_fips VARCHAR,
  report_year NUMBER, case_status VARCHAR, sex VARCHAR, age_category_years VARCHAR,
  frequency NUMBER, source_value_status VARIANT, geography_semantics VARCHAR,
  source_resolution VARCHAR, temporal_window VARCHAR, caveat VARCHAR,
  retrieved_at TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_SNAPSHOTS (
  ingestion_run_id VARCHAR NOT NULL, data_source_version_id VARCHAR NOT NULL,
  content_sha256 VARCHAR(64) NOT NULL, validation_id VARCHAR NOT NULL,
  row_count NUMBER NOT NULL, validated_at TIMESTAMP_LTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_PUBLICATIONS (
  data_source_version_id VARCHAR NOT NULL, ingestion_run_id VARCHAR,
  content_sha256 VARCHAR(64), revision NUMBER NOT NULL DEFAULT 0,
  published_at TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_PUBLICATION_EVENTS (
  event_id VARCHAR NOT NULL, data_source_version_id VARCHAR NOT NULL,
  previous_run_id VARCHAR, ingestion_run_id VARCHAR NOT NULL,
  revision NUMBER NOT NULL, reason VARCHAR NOT NULL, created_at TIMESTAMP_LTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_OPERATION_LEASE (
  resource_key VARCHAR NOT NULL, lease_owner VARCHAR, expires_at TIMESTAMP_LTZ,
  publication_enabled BOOLEAN NOT NULL DEFAULT FALSE
);
INSERT INTO GOVERNANCE.CDC_OPERATION_LEASE(resource_key)
SELECT 'cdc_lyme_x5j9_wybp' WHERE NOT EXISTS (
  SELECT 1 FROM GOVERNANCE.CDC_OPERATION_LEASE WHERE resource_key='cdc_lyme_x5j9_wybp'
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_METADATA_CHECKS (
  check_id VARCHAR NOT NULL, checked_at TIMESTAMP_LTZ NOT NULL,
  metadata_sha256 VARCHAR(64), status VARCHAR NOT NULL, error_classification VARCHAR
);
CREATE TABLE IF NOT EXISTS GOVERNANCE.CDC_INCIDENTS (
  incident_key VARCHAR NOT NULL, incident_type VARCHAR NOT NULL,
  related_run_id VARCHAR, created_at TIMESTAMP_LTZ NOT NULL,
  delivered_at TIMESTAMP_LTZ, delivery_reference VARCHAR
);

GRANT SELECT, INSERT ON TABLE CONFORMED.CDC_VALIDATED_SNAPSHOTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE GOVERNANCE.CDC_SNAPSHOTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE GOVERNANCE.CDC_PUBLICATIONS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE GOVERNANCE.CDC_PUBLICATION_EVENTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, UPDATE ON TABLE GOVERNANCE.CDC_OPERATION_LEASE TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE GOVERNANCE.CDC_METADATA_CHECKS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE GOVERNANCE.CDC_INCIDENTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT ON TABLE GOVERNANCE.DATA_QUALITY_RESULTS TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;

-- Publication starts empty. The explicit bootstrap command must validate and
-- copy the current source before replacing its existing public view.
