USE DATABASE {{ DATABASE }};

-- DEV-only cleanup after the scoped V046 AccountAdmin execution. The governed
-- view owner receives only the underlying reads required to own this one view.
GRANT SELECT ON TABLE CONFORMED.CDC_HISTORICAL_VALIDATED_SNAPSHOTS
  TO ROLE OH_LYME_DEV_GOVERNED_VIEW_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.CDC_PUBLICATIONS
  TO ROLE OH_LYME_DEV_GOVERNED_VIEW_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.DATA_SOURCE_VERSIONS
  TO ROLE OH_LYME_DEV_GOVERNED_VIEW_OWNER;

GRANT OWNERSHIP ON VIEW CONFORMED.CONFORMED_CDC_LYME_QTBI_XD4I
  TO ROLE OH_LYME_DEV_GOVERNED_VIEW_OWNER COPY CURRENT GRANTS;

-- Remove the temporary metadata read added solely so V046 could create the
-- historical view. The underlying object owners and runtime grants are intact.
REVOKE SELECT ON TABLE GOVERNANCE.DATA_SOURCE_VERSIONS FROM ROLE ACCOUNTADMIN;
