USE DATABASE {{ DATABASE }};

-- PROD only. The migration deployer owns the storage objects and grants only
-- the writes and reads required by the runtime and governed-view owner.
CREATE TABLE IF NOT EXISTS RAW.CDC_LYME_QTBI_XD4I (
 payload VARIANT NOT NULL, data_source_version_id VARCHAR NOT NULL,
 ingestion_run_id VARCHAR NOT NULL, artifact_id VARCHAR NOT NULL,
 source_url VARCHAR NOT NULL, redacted_source_query VARCHAR, source_record_id VARCHAR,
 source_row_hash VARCHAR(64) NOT NULL, publisher_updated_at TIMESTAMP_LTZ,
 retrieved_at TIMESTAMP_LTZ NOT NULL,
 snowflake_loaded_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS CONFORMED.CDC_HISTORICAL_VALIDATED_SNAPSHOTS (
 source_record_id VARCHAR, payload VARIANT, data_source_version_id VARCHAR,
 ingestion_run_id VARCHAR, artifact_id VARCHAR, county_fips VARCHAR,
 report_year NUMBER, case_status VARCHAR, sex VARCHAR, age_category_years VARCHAR,
 frequency NUMBER, source_value_status VARIANT, geography_semantics VARCHAR,
 source_resolution VARCHAR, temporal_window VARCHAR, caveat VARCHAR,
 retrieved_at TIMESTAMP_LTZ
);
CREATE VIEW IF NOT EXISTS CONFORMED.CONFORMED_CDC_LYME_QTBI_XD4I AS
SELECT snapshot.* FROM CONFORMED.CDC_HISTORICAL_VALIDATED_SNAPSHOTS snapshot
JOIN GOVERNANCE.CDC_PUBLICATIONS publication
 ON snapshot.data_source_version_id=publication.data_source_version_id
 AND snapshot.ingestion_run_id=publication.ingestion_run_id
JOIN GOVERNANCE.DATA_SOURCE_VERSIONS version
 ON version.data_source_version_id=snapshot.data_source_version_id
WHERE version.resource_key='cdc_lyme_qtbi_xd4i'
 AND version.status='APPROVED' AND version.retired_at IS NULL;
INSERT INTO GOVERNANCE.CDC_OPERATION_LEASE(resource_key,publication_enabled)
SELECT 'cdc_lyme_qtbi_xd4i',TRUE WHERE NOT EXISTS (
 SELECT 1 FROM GOVERNANCE.CDC_OPERATION_LEASE WHERE resource_key='cdc_lyme_qtbi_xd4i'
);
GRANT SELECT, INSERT ON TABLE RAW.CDC_LYME_QTBI_XD4I
 TO ROLE OH_LYME_PROD_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE CONFORMED.CDC_HISTORICAL_VALIDATED_SNAPSHOTS
 TO ROLE OH_LYME_PROD_PIPELINE_RUNTIME;
GRANT SELECT ON VIEW CONFORMED.CONFORMED_CDC_LYME_QTBI_XD4I
 TO ROLE OH_LYME_PROD_PIPELINE_RUNTIME;
GRANT SELECT ON TABLE RAW.CDC_LYME_QTBI_XD4I
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER;
GRANT SELECT ON TABLE CONFORMED.CDC_HISTORICAL_VALIDATED_SNAPSHOTS
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.CDC_PUBLICATIONS
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER;
GRANT SELECT ON TABLE GOVERNANCE.DATA_SOURCE_VERSIONS
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER;
GRANT SELECT, INSERT ON TABLE GOVERNANCE.SCHEMA_MIGRATIONS
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER;
GRANT OWNERSHIP ON VIEW CONFORMED.CONFORMED_CDC_LYME_QTBI_XD4I
 TO ROLE OH_LYME_PROD_GOVERNED_VIEW_OWNER COPY CURRENT GRANTS;
