-- DEV-only repair: this procedure runs with a dedicated owner that has only
-- the budget-ledger reads/writes required to enforce the extraction limit.
USE DATABASE {{ DATABASE }};

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  WORKLOAD VARCHAR, REQUEST_ID VARCHAR, PROVIDER VARCHAR, MODEL_IDENTIFIER VARCHAR,
  ESTIMATED_COST_USD NUMBER, DAILY_LIMIT_USD NUMBER, MONTHLY_LIMIT_USD NUMBER
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  daily_used NUMBER;
  monthly_used NUMBER;
  allowed BOOLEAN;
BEGIN
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :daily_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('day', CURRENT_TIMESTAMP());
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :monthly_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('month', CURRENT_TIMESTAMP());
  allowed := daily_used + ESTIMATED_COST_USD <= DAILY_LIMIT_USD
             AND monthly_used + ESTIMATED_COST_USD <= MONTHLY_LIMIT_USD;
  IF (allowed) THEN
    INSERT INTO GOVERNANCE.LLM_BUDGET_USAGE VALUES
      (UUID_STRING(), :WORKLOAD, :REQUEST_ID, :PROVIDER, :MODEL_IDENTIFIER,
       :ESTIMATED_COST_USD, NULL, 'reserved', CURRENT_TIMESTAMP());
  END IF;
  RETURN OBJECT_CONSTRUCT('allowed', :allowed, 'daily_used_usd', :daily_used,
                          'monthly_used_usd', :monthly_used);
END;
$$;

GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
