-- Env-neutral: Snowflake rejects UUID_STRING() inside VALUES in SQL procedures.
-- V057 fixed this on DEV only; PROD still had the V025 VALUES form and failed
-- chat budget reservation. Recreate with INSERT...SELECT and grant API readers.
USE DATABASE {{ DATABASE }};

CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  WORKLOAD VARCHAR, REQUEST_ID VARCHAR, PROVIDER VARCHAR, MODEL_IDENTIFIER VARCHAR,
  ESTIMATED_COST_USD NUMBER, DAILY_LIMIT_USD NUMBER, MONTHLY_LIMIT_USD NUMBER
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  daily_used NUMBER;
  monthly_used NUMBER;
  allowed BOOLEAN;
BEGIN
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :daily_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('day', CURRENT_TIMESTAMP());
  SELECT COALESCE(SUM(estimated_cost_usd),0) INTO :monthly_used FROM GOVERNANCE.LLM_BUDGET_USAGE
    WHERE workload = :WORKLOAD AND status IN ('reserved','used')
      AND recorded_at >= DATE_TRUNC('month', CURRENT_TIMESTAMP());
  allowed := daily_used + ESTIMATED_COST_USD <= DAILY_LIMIT_USD
             AND monthly_used + ESTIMATED_COST_USD <= MONTHLY_LIMIT_USD;
  IF (allowed) THEN
    INSERT INTO GOVERNANCE.LLM_BUDGET_USAGE (
      budget_usage_id, workload, request_id, provider, model_identifier,
      estimated_cost_usd, actual_cost_usd, status, recorded_at
    ) SELECT UUID_STRING(), :WORKLOAD, :REQUEST_ID, :PROVIDER, :MODEL_IDENTIFIER,
             :ESTIMATED_COST_USD, NULL, 'reserved', CURRENT_TIMESTAMP();
  END IF;
  RETURN OBJECT_CONSTRUCT('allowed', :allowed, 'daily_used_usd', :daily_used,
                          'monthly_used_usd', :monthly_used);
END;
$$;

GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_RESERVE_KG_LLM_BUDGET(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, NUMBER, NUMBER)
  TO ROLE OH_LYME_API_READER;

-- Chat citations expose passage_ids[]; V025 persist read passage_id and NOT NULL failed
-- the insert after the answered turn was already written, surfacing as HTTP 503.
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(
  CONVERSATION_ID VARCHAR, TOKEN_HASH VARCHAR, NETWORK_HASH VARCHAR, TURN_ID VARCHAR,
  REQUEST_ID VARCHAR, ROLE VARCHAR, BODY VARCHAR, STATUS VARCHAR, CITATIONS VARIANT
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  token_mismatch EXCEPTION (-20110, 'Conversation capability is invalid');
  existing_count NUMBER;
  matching_count NUMBER;
BEGIN
  SELECT COUNT(*), COUNT_IF(token_hash = :TOKEN_HASH)
    INTO :existing_count, :matching_count
    FROM GOVERNANCE.KG_CONVERSATIONS WHERE conversation_id = :CONVERSATION_ID;
  IF (existing_count = 1 AND matching_count <> 1) THEN RAISE token_mismatch; END IF;
  MERGE INTO GOVERNANCE.KG_CONVERSATIONS target
  USING (SELECT :CONVERSATION_ID id) source ON target.conversation_id = source.id
  WHEN NOT MATCHED THEN INSERT
    (conversation_id, token_hash, network_hash, expires_at)
    VALUES (:CONVERSATION_ID, :TOKEN_HASH, :NETWORK_HASH, DATEADD(day, 30, CURRENT_TIMESTAMP()))
  WHEN MATCHED AND target.token_hash = :TOKEN_HASH THEN UPDATE SET
    last_turn_at = CURRENT_TIMESTAMP(), expires_at = DATEADD(day, 30, CURRENT_TIMESTAMP());
  INSERT INTO GOVERNANCE.KG_CONVERSATION_TURNS
    (turn_id, conversation_id, request_id, role, body, status)
    VALUES (:TURN_ID, :CONVERSATION_ID, :REQUEST_ID, :ROLE, :BODY, :STATUS);
  INSERT INTO GOVERNANCE.KG_TURN_CITATIONS
    SELECT
      :TURN_ID,
      value:citation_id::VARCHAR,
      value:pmid::VARCHAR,
      COALESCE(value:passage_id::VARCHAR, GET(value:passage_ids, 0)::VARCHAR),
      value:claim_ids::ARRAY
    FROM TABLE(FLATTEN(INPUT => :CITATIONS))
    WHERE COALESCE(value:passage_id::VARCHAR, GET(value:passage_ids, 0)::VARCHAR) IS NOT NULL;
  RETURN OBJECT_CONSTRUCT('persisted', TRUE, 'expires_in_days', 30);
END;
$$;

GRANT USAGE ON PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT)
  TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT)
  TO ROLE OH_LYME_{{ ENV }}_API_RUNTIME;
GRANT USAGE ON PROCEDURE GOVERNANCE.SP_PERSIST_KG_CONVERSATION_TURN(
  VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT)
  TO ROLE OH_LYME_API_READER;
