-- Phase 2: persist canonical payloads and normalized rows for fresh-process resume.
-- Source-faithful response bytes remain in GOVERNANCE.RAW_ARTIFACTS/Spaces.

USE DATABASE {{ DATABASE }};

CREATE TABLE IF NOT EXISTS GOVERNANCE.INGESTION_RUN_PAYLOADS (
    ingestion_run_id VARCHAR PRIMARY KEY,
    payload VARIANT NOT NULL,
    value_sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.INGESTION_RUN_NORMALIZED (
    ingestion_run_id VARCHAR PRIMARY KEY,
    records VARIANT NOT NULL,
    value_sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT ON TABLE GOVERNANCE.INGESTION_RUN_PAYLOADS
    TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
GRANT SELECT, INSERT ON TABLE GOVERNANCE.INGESTION_RUN_NORMALIZED
    TO ROLE OH_LYME_{{ ENV }}_PIPELINE_RUNTIME;
