-- DEV-only least-privilege grants for the V077 owner-rights restricted loader.
-- The procedure writes redacted governance evidence and a derived-only publication record.
USE DATABASE {{ DATABASE }};

GRANT INSERT ON TABLE GOVERNANCE.INGESTION_REQUESTS TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
GRANT INSERT ON TABLE GOVERNANCE.DATA_QUALITY_RESULTS TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
GRANT INSERT ON TABLE GOVERNANCE.INGESTION_PUBLICATIONS TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
