-- Epic #252: least-privilege correction for the protected semantic-release workflow.
--
-- V071 established immutable semantic storage but omitted the release workflow
-- identity.  The protected workflow performs candidate assembly plus the
-- reviewed publish/rollback pointer transitions.  Grant only the table actions
-- exercised by those paths; it receives neither raw/conformed source access,
-- schema ownership, nor DELETE.
USE DATABASE {{ DATABASE }};

GRANT USAGE ON SCHEMA PRESENTATION
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;

GRANT SELECT, INSERT, UPDATE ON TABLE PRESENTATION.SEMANTIC_RELEASES
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_DATA_SOURCES
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_DATASETS
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_INDICATORS
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_MEASURES
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_COUNTY_ATLAS
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT ON TABLE PRESENTATION.SEMANTIC_OBSERVATIONS
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT INSERT ON TABLE PRESENTATION.SEMANTIC_RELEASE_EVENTS
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
GRANT SELECT, INSERT, UPDATE ON TABLE PRESENTATION.SEMANTIC_RELEASE_POINTER
    TO ROLE OH_LYME_{{ ENV }}_MIGRATION_DEPLOYER;
