-- DATA #443: candidate DEV-only reads for the existing protected release builder.
-- Apply only after separate owner authorization for these exact source objects.
USE DATABASE {{ DATABASE }};

GRANT SELECT ON VIEW CONFORMED.CONFORMED_CDC_LYME_X5J9_WYBP
    TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
GRANT SELECT ON TABLE CONFORMED.GOVERNED_SOURCE_RECORDS
    TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
GRANT SELECT ON TABLE CONFORMED.RESTRICTED_CDC_PATHOGEN_COUNTY_STATUS
    TO ROLE OH_LYME_DEV_MIGRATION_DEPLOYER;
