-- DATA #496: read-only audit. Run identity first in each named connection.
-- ATLAS_DEV_READ, ATLAS_DEV_OWNER, ATLAS_PROD_RUNTIME_AUDIT only.
SELECT CURRENT_TIMESTAMP() AS audit_time, CURRENT_USER(), CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_WAREHOUSE();
SELECT TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('PRESENTATION','GOVERNANCE','KNOWLEDGE_GRAPH')
AND (TABLE_NAME ILIKE '%SEMANTIC%' OR TABLE_NAME ILIKE '%DERIVED_RESULTS%'
 OR TABLE_NAME ILIKE '%INGESTION_RUN%' OR TABLE_NAME ILIKE '%PHYSICAL%'
 OR TABLE_NAME ILIKE '%PAPERS%' OR TABLE_NAME ILIKE '%CORPUS%' OR TABLE_NAME ILIKE '%RETRIEVAL%')
ORDER BY TABLE_SCHEMA,TABLE_NAME;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA='PRESENTATION' ORDER BY TABLE_NAME;
SELECT CURRENT_TIMESTAMP() AS audit_time,RELEASE_ID FROM PRESENTATION.CURRENT_RELEASE_V;
-- DEV OWNER only: approved measure metadata and bounded existing run lineage.
SELECT RELEASE_ID,MEASURE_ID,UNIT,TEMPORAL_RESOLUTION FROM PRESENTATION.SEMANTIC_MEASURES
WHERE MEASURE_ID ILIKE '%nclim%' OR MEASURE_ID ILIKE '%climate%';
SELECT INGESTION_RUN_ID,RESOURCE_KEY,STATUS,CODE_VERSION,CONFIG_SHA256,STARTED_AT,COMPLETED_AT
FROM GOVERNANCE.INGESTION_RUNS
WHERE RESOURCE_KEY ILIKE '%nclim%' OR RESOURCE_KEY ILIKE '%nlcd%' ORDER BY STARTED_AT;
-- DEV READ or PROD RUNTIME separately; actual counts, not publication counts.
SELECT CURRENT_TIMESTAMP() AS audit_time,'PAPERS' AS object_name,COUNT(*) AS n FROM KNOWLEDGE_GRAPH.PAPERS
UNION ALL SELECT CURRENT_TIMESTAMP(),'RETRIEVAL_CORPUS_UNITS',COUNT(*) FROM KNOWLEDGE_GRAPH.RETRIEVAL_CORPUS_UNITS;
-- PROD RUNTIME: visibility probe; denied object means role-scoped blocker.
SELECT CURRENT_TIMESTAMP() AS audit_time,COUNT(*) AS n FROM PRESENTATION.CURRENT_COUNTY_ATLAS_V;
SELECT CURRENT_TIMESTAMP() AS audit_time,COUNT(*) AS n FROM PRESENTATION.CURRENT_MEASURE_METADATA_V WHERE MEASURE_ID ILIKE '%nclim%';
