-- Run separately with ATLAS_DEV_READ and ATLAS_PROD_RUNTIME_AUDIT.
-- Capture identity first. No writes, publication, role switching or grant changes.
SELECT CURRENT_TIMESTAMP() AS AUDIT_TIME,CURRENT_USER() AS AUDIT_USER,
 CURRENT_ROLE() AS AUDIT_ROLE,CURRENT_DATABASE() AS AUDIT_DATABASE,
 CURRENT_WAREHOUSE() AS AUDIT_WAREHOUSE;
SELECT RELEASE_ID FROM PRESENTATION.CURRENT_RELEASE_V;
SELECT COUNT(*) AS COUNTY_ROWS FROM PRESENTATION.CURRENT_COUNTY_ATLAS_V;
SELECT COUNT(*) AS PAPER_ROWS FROM KNOWLEDGE_GRAPH.PAPERS;
SELECT COUNT(*) AS CORPUS_ROWS FROM KNOWLEDGE_GRAPH.RETRIEVAL_CORPUS_UNITS;
-- Metadata is role-visible, estimated, and never establishes absence.
SELECT TABLE_SCHEMA,TABLE_NAME,ROW_COUNT FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%DERIVED_RESULTS%'
 OR TABLE_NAME ILIKE '%COVERAGE%RESULT%'
 OR TABLE_NAME ILIKE '%PRIORITY%RESULT%'
ORDER BY TABLE_SCHEMA,TABLE_NAME;
