-- DATA #627 protected account-level bootstrap. Do not run from a normal migration.
-- Requires a separately reviewed PROD administrative action and context proof.
-- Review SHOW GRANTS before replaying; IF NOT EXISTS does not validate drift.
CREATE ROLE IF NOT EXISTS OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
CREATE ROLE IF NOT EXISTS OH_LYME_PROD_ML_PUBLISHER;

GRANT USAGE ON DATABASE ONE_HEALTH_LYME_GAP_ATLAS_PROD
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.FEATURE_STORE
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.PRESENTATION
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.GOVERNANCE
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT CREATE TABLE, CREATE PROCEDURE
  ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.FEATURE_STORE
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT CREATE VIEW ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.PRESENTATION
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT SELECT ON TABLE ONE_HEALTH_LYME_GAP_ATLAS_PROD.PRESENTATION.SEMANTIC_RELEASES
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT SELECT ON TABLE ONE_HEALTH_LYME_GAP_ATLAS_PROD.PRESENTATION.SEMANTIC_COUNTY_ATLAS
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT SELECT, INSERT ON TABLE ONE_HEALTH_LYME_GAP_ATLAS_PROD.GOVERNANCE.SCHEMA_MIGRATIONS
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT USAGE ON WAREHOUSE OH_LYME_PROD_INGEST_XS_WH
  TO ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER;
GRANT ROLE OH_LYME_PROD_TIER1_PUBLICATION_OWNER
  TO USER OH_LYME_PROD_MIGRATION_DEPLOY_SVC;

GRANT USAGE ON DATABASE ONE_HEALTH_LYME_GAP_ATLAS_PROD
  TO ROLE OH_LYME_PROD_ML_PUBLISHER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS_PROD.FEATURE_STORE
  TO ROLE OH_LYME_PROD_ML_PUBLISHER;
GRANT USAGE ON WAREHOUSE OH_LYME_PROD_INGEST_XS_WH
  TO ROLE OH_LYME_PROD_ML_PUBLISHER;

-- Publisher service user and role-restricted PAT are a separately attributable
-- security action after role and V141 review. No token is created here.
