CREATE DATABASE IF NOT EXISTS ONE_HEALTH_LYME_GAP_ATLAS;
USE DATABASE ONE_HEALTH_LYME_GAP_ATLAS;
CREATE SCHEMA IF NOT EXISTS LANDING;
CREATE SCHEMA IF NOT EXISTS PRESENTATION;

CREATE TABLE IF NOT EXISTS LANDING.DATASET_RELEASE (
  RELEASE_ID VARCHAR PRIMARY KEY,
  SCHEMA_VERSION VARCHAR NOT NULL,
  GENERATED_AT TIMESTAMP_TZ NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  SCOPE VARCHAR NOT NULL,
  BUNDLE_SHA256 VARCHAR(64) NOT NULL,
  SCORE_DEFAULTS VARIANT NOT NULL,
  METHODOLOGY_VERSION VARCHAR NOT NULL,
  LIMITATIONS VARCHAR NOT NULL,
  IS_CURRENT BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS LANDING.SOURCE_METADATA (
  RELEASE_ID VARCHAR NOT NULL,
  SOURCE_KEY VARCHAR NOT NULL,
  LABEL VARCHAR NOT NULL,
  VINTAGE VARCHAR NOT NULL,
  SOURCE_URL VARCHAR NOT NULL,
  NOTE VARCHAR NOT NULL,
  PRIMARY KEY (RELEASE_ID, SOURCE_KEY)
);

CREATE TABLE IF NOT EXISTS LANDING.COUNTY_ATLAS (
  RELEASE_ID VARCHAR NOT NULL,
  FIPS VARCHAR(5) NOT NULL,
  COUNTY VARCHAR NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  STATE_NAME VARCHAR NOT NULL,
  POPULATION NUMBER,
  IN_CONTIGUOUS_TICK_SCOPE BOOLEAN NOT NULL,
  HUMAN_STATUS VARCHAR NOT NULL,
  CASE_COUNT_FLOOR_2023 NUMBER,
  INCIDENCE_FLOOR_2023 FLOAT,
  STATE_UNALLOCATED_RECORDS_2023 NUMBER,
  TICK_STATUS VARCHAR NOT NULL,
  SCAPULARIS_STATUS VARCHAR,
  PACIFICUS_STATUS VARCHAR,
  BURGDORFERI_STATUS VARCHAR NOT NULL,
  SVI_PERCENTILE FLOAT,
  UNINSURED_PERCENTILE FLOAT,
  UNINSURED_PERCENT FLOAT,
  RUCC_2023 NUMBER,
  EVIDENCE_COMPLETENESS NUMBER NOT NULL,
  DEFAULT_SCORE VARIANT NOT NULL,
  GEOMETRY_JSON VARIANT NOT NULL,
  GEOGRAPHY GEOGRAPHY NOT NULL,
  PRIMARY KEY (RELEASE_ID, FIPS)
);

CREATE OR REPLACE VIEW PRESENTATION.CURRENT_RELEASE_V AS
SELECT RELEASE_ID, SCHEMA_VERSION, GENERATED_AT, LOADED_AT, SCOPE, BUNDLE_SHA256,
       SCORE_DEFAULTS, METHODOLOGY_VERSION, LIMITATIONS
FROM LANDING.DATASET_RELEASE WHERE IS_CURRENT;

CREATE OR REPLACE VIEW PRESENTATION.CURRENT_SOURCE_METADATA_V AS
SELECT S.RELEASE_ID, S.SOURCE_KEY, S.LABEL, S.VINTAGE, S.SOURCE_URL, S.NOTE
FROM LANDING.SOURCE_METADATA S
JOIN LANDING.DATASET_RELEASE R USING (RELEASE_ID)
WHERE R.IS_CURRENT;

CREATE OR REPLACE VIEW PRESENTATION.CURRENT_COUNTY_ATLAS_V AS
SELECT C.*
FROM LANDING.COUNTY_ATLAS C
JOIN LANDING.DATASET_RELEASE R USING (RELEASE_ID)
WHERE R.IS_CURRENT;

