-- Run with a role authorized to create roles/users and grant privileges.
CREATE ROLE IF NOT EXISTS OH_LYME_DATA_LOADER;
CREATE ROLE IF NOT EXISTS OH_LYME_API_READER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OH_LYME_DATA_LOADER;
GRANT USAGE ON DATABASE ONE_HEALTH_LYME_GAP_ATLAS TO ROLE OH_LYME_DATA_LOADER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.LANDING TO ROLE OH_LYME_DATA_LOADER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.PRESENTATION TO ROLE OH_LYME_DATA_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.LANDING TO ROLE OH_LYME_DATA_LOADER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OH_LYME_API_READER;
GRANT USAGE ON DATABASE ONE_HEALTH_LYME_GAP_ATLAS TO ROLE OH_LYME_API_READER;
GRANT USAGE ON SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.PRESENTATION TO ROLE OH_LYME_API_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.PRESENTATION TO ROLE OH_LYME_API_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ONE_HEALTH_LYME_GAP_ATLAS.PRESENTATION TO ROLE OH_LYME_API_READER;

CREATE USER IF NOT EXISTS OH_LYME_API_SVC TYPE=SERVICE DEFAULT_ROLE=OH_LYME_API_READER;
GRANT ROLE OH_LYME_API_READER TO USER OH_LYME_API_SVC;

-- Register the generated public key separately. Never store the private key here.
-- ALTER USER OH_LYME_API_SVC ADD KEY PAIR OH_LYME_API_2026 PUBLIC_KEY='<public-key>' ROLE_RESTRICTION='OH_LYME_API_READER';

